"""Shared constants for the P2P chat system."""

DEFAULT_BOOTSTRAP_HOST = "127.0.0.1"
DEFAULT_BOOTSTRAP_PORT = 9000
DEFAULT_PEER_HOST = "127.0.0.1"

ENCODING = "utf-8"
SOCKET_BACKLOG = 50
SOCKET_TIMEOUT_SECONDS = 3.0
ACK_TIMEOUT_SECONDS = 2.5
HEARTBEAT_INTERVAL_SECONDS = 10.0
PEER_STALE_AFTER_SECONDS = 30.0

MAX_MESSAGE_BYTES = 1024 * 1024

MESSAGE_TYPES = {
    "REGISTER",
    "PEER_LIST",
    "CHAT",
    "GROUP_CHAT",
    "BROADCAST",
    "SYSTEM",
    "FILE_META",
    "FILE_CHUNK",
    "FILE_END",
    "FILE_ACK",
    "FILE_ERROR",
    "ACK",
    "HEARTBEAT",
    "DISCONNECT",
    "GROUP_CREATE",
    "GROUP_LIST",
    "GROUP_GET",
    "GROUP_JOIN",
    "GROUP_ADD_MEMBER",
    "GROUP_REMOVE_MEMBER",
    "GROUP_LEAVE",
    "OFFLINE_QUEUE",
    "OFFLINE_PENDING",
    "OFFLINE_MARK_DELIVERED",
    "ERROR",
}

OFFLINE_RETRY_INTERVAL_SECONDS = 5.0
FILE_CHUNK_BYTES = 64 * 1024
MAX_FILE_SIZE_MB = 50
